### ISSUE TITLE
Failed tests

### ISSUE THREAD

**Issue by jitAbhra** [hplgit/odespy#7]
Hi @hplgit @liweiw @rothnic,

I have installed odespy using anaconda on debian 8 from github. During installation there was no problem. The output is 

```
running install
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building library "_odepack" sources
building library "_rkc" sources
building library "_rkf45" sources
building library "_radau5" sources
building extension "odespy._odepack" sources
f2py options: []
  adding 'build/src.linux-x86_64-2.7/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-2.7' to include_dirs.
  adding 'build/src.linux-x86_64-2.7/odespy/odepack/_odepack-f2pywrappers.f' to sources.
building extension "odespy._rkc" sources
f2py options: []
  adding 'build/src.linux-x86_64-2.7/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-2.7' to include_dirs.
  adding 'build/src.linux-x86_64-2.7/odespy/rkc/_rkc-f2pywrappers.f' to sources.
building extension "odespy._rkf45" sources
f2py options: []
  adding 'build/src.linux-x86_64-2.7/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-2.7' to include_dirs.
building extension "odespy._radau5" sources
f2py options: []
  adding 'build/src.linux-x86_64-2.7/fortranobject.c' to sources.
  adding 'build/src.linux-x86_64-2.7' to include_dirs.
building data_files sources
build_src: building npy-pkg config files
running build_py
running build_clib
customize UnixCCompiler
customize UnixCCompiler using build_clib
customize Gnu95FCompiler
Found executable /usr/bin/gfortran
customize Gnu95FCompiler
customize Gnu95FCompiler using build_clib
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
customize Gnu95FCompiler
customize Gnu95FCompiler
customize Gnu95FCompiler using build_ext
running install_lib
running install_data
running install_egg_info
Removing /home/abhra/software/anaconda/lib/python2.7/site-packages/odespy-0.3.00.3.0-py2.7.egg-info
Writing /home/abhra/software/anaconda/lib/python2.7/site-packages/odespy-0.3.00.3.0-py2.7.egg-info
running install_clib
```

Then I moved to Demos and start running the demo files.

For all demo_Lso*.py  it is not running. 

```
$ anaconda demo_Lsode_Lsoda_1.py 
/home/abhra/software/anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "demo_Lsode_Lsoda_1.py", line 42, in <module>
    m = method(f, rtol=rtol, atol=atol, jac=jac)
  File "/home/abhra/software/anaconda/lib/python2.7/site-packages/odespy/solvers.py", line 661, in __init__
    self.initialize()
  File "/home/abhra/software/anaconda/lib/python2.7/site-packages/odespy/odepack.py", line 649, in initialize
    raise ImportError('Cannot find the extension module _odepack.\nRun setup.py again and investigate why _odepack.so was not successfully built.')
ImportError: Cannot find the extension module _odepack.
Run setup.py again and investigate why _odepack.so was not successfully built.
```

for demo_RKC_2.py
```
anaconda demo_RKC_2.py 
/home/abhra/software/anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
This test will take several minutes, please wait...
Traceback (most recent call last):
  File "demo_RKC_2.py", line 80, in <module>
    m = method(f, rtol=rtol, atol=atol, spcrad=spcrad, jac_constant=jac_constant)
  File "/home/abhra/software/anaconda/lib/python2.7/site-packages/odespy/solvers.py", line 661, in __init__
    self.initialize()
  File "/home/abhra/software/anaconda/lib/python2.7/site-packages/odespy/rkc.py", line 161, in initialize
    raise ImportError('Cannot find the extension module _rkc.\nRemove build directory, run setup.py again and investigate why _rkc.so was not successfully built.')
ImportError: Cannot find the extension module _rkc.
Remove build directory, run setup.py again and investigate why _rkc.so was not successfully built.
```

also for Radau Demos

```
anaconda demo_Radau5_2.py 
/home/abhra/software/anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "demo_Radau5_2.py", line 41, in <module>
    m = method(f, rtol=rtol, atol=atol, jac=jac)
  File "/home/abhra/software/anaconda/lib/python2.7/site-packages/odespy/solvers.py", line 661, in __init__
    self.initialize()
  File "/home/abhra/software/anaconda/lib/python2.7/site-packages/odespy/radau5.py", line 127, in initialize
    raise ImportError('Cannot find the extension module _radau5.\nRun setup.py again and investigate why _radau5.so was not successfully built.')
ImportError: Cannot find the extension module _radau5.
Run setup.py again and investigate why _radau5.so was not successfully built.
```

It would be nice if some help can be provided. Thanks.

abhra

update
--- 

after going to anaconda/lib/python2.7/site-packages/odespy, I tried to import _odepack. This error is displayed

> ImportError: /home/abhra/software/anaconda/bin/../lib/libgfortran.so.3: version `GFORTRAN_1.4' not found (required by ./_odepack.so)

**Comment by jitAbhra** [comment]
Cool!. 
Following [this link](http://stackoverflow.com/questions/9628273/libgfortran-version-gfortran-1-4-not-found) 
```
cd ~/abhra/anaconda/lib/
mv libgfortran.so.3.0.0 libgfortran.so.3.0.0.bak; ln -sf /usr/lib/x86_64-linux-gnu/libgfortran.so.3.0.0 libgfortran.so.3.0.0
```
Now everything should fall in place.

**Comment by hplgit** [comment]
Great, many thanks for finding out of this. I have made a summary in the README.md file in the root directory.
